GET http://127.0.0.1:8000/terms HTTP/1.1

###

GET http://127.0.0.1:8000/terms/1 HTTP/1.1

###

POST http://127.0.0.1:8000/terms HTTP/1.1
content-type: application/json

{
    "word": "Архитектура программы",
    "meaning": "Структурное представление программной системы, включающее описание компонентов, их взаимодействий, поведения и ограничений. Архитектура определяет основные принципы, обеспечивающие надежность, масштабируемость и производительность системы."
}

###

POST http://127.0.0.1:8000/terms HTTP/1.1
content-type: application/json

{
    "word": "Контейнеризация",
    "meaning": "Технология упаковки программного обеспечения и всех его зависимостей в изолированный контейнер для обеспечения согласованности среды выполнения на разных платформах. Примеры инструментов: Docker, Podman."
}

###

POST http://127.0.0.1:8000/terms HTTP/1.1
content-type: application/json

{
    "word": "Непрерывное развертывание",
    "meaning": "Подход в разработке программного обеспечения, при котором изменения в коде автоматически проходят все этапы подготовки и развертываются на рабочем сервере без ручного вмешательства. Это обеспечивает быстрое обновление системы и минимизацию времени вывода продукта на рынок."
}

###

PUT http://127.0.0.1:8000/terms/1 HTTP/1.1
content-type: application/json

{
    "word": "Архитектура программной системы"
}

###

DELETE http://127.0.0.1:8000/terms/2 HTTP/1.1
content-type: application/json
